





public class aaaa {
	public static void main(String[] args) {
		// TODO todo.generated by zoer
		System.out.println("@Override\n" +"public void save(Bean bean) throws Exception {\n" +
				"\tString sql = \"\";\n" +
				"\tPreparedDBUtil pdb = new PreparedDBUtil();\n" +
				"\tpdb.preparedInsert(dsName, sql);\n" +
				"\tint c=1; \n" +
				"\tpdb.setString(c++, bean.get()); \n" +
				"\t \n" +
				"\tpdb.executePrepared(); \n" +
				"\t}");
		
		System.out.println(
				"@Override\n" +
				"public void update(Bean bean) throws Exception {\n" +
				"\tString sql = \"\";\n" +
				"\tPreparedDBUtil pdb = new PreparedDBUtil();\n" +
				"\tpdb.preparedUpdate(dsName, sql);\n" +
				"\tint c=1; \n" +
				"\tpdb.setString(c++, bean.get()); \n" +
				"\t \n" +
				"\tpdb.executePrepared(); \n" +
				"\t}");
		
		System.out.println(
				"@Override\n" +
				"public List<Bean> getListBy(Bean bean) throws Exception {\n" +
				"\tList<Bean> list = new ArrayList<Bean>();\n" +
				"\tStringBuffer sql = new StringBuffer();\n" +
				"\t// 拼接sql beg\n" +
				"\tsql.append(\"\");\n" +
				"\t\n" +
				"\t// 拼接sql end\n" +
				"\tsql.append(\"1=1\");\n" +
				"\tList<String> codition = new ArrayList<String>();\n" +
				"\tif (!StringUtil.isBlank(bean.get())) {\n" +
				"\t\tsql.append(\" and xxx = ?\"); //sql.append(\" and xxx like ?\");\n" +
				"\t\tcodition.add(StringUtil.deNull(bean.get()));//codition.add(\"%\"+StringUtil.deNull(bean.get())+\"%\");\n" +
				"\t}\n" +
				"\tPreparedDBUtil pdb = new PreparedDBUtil();\n" +
				"\tpdb.preparedSelect(dsName, sql.toString());\n" +
				"\tint c=1; \n" +
				"\tfor (int i = 0; i < codition.size(); i++) { \n" +
				"\t\tpdb.setString(c++, codition.get(i)); \n" +
				"\t }\n" +
				"\tpdb.executePrepared(); \n" +
				"\tfor (int i = 0; i < pdb.size(); i++) { \n" +
				"\t\tBean temp = new Bean(); \n" +
				"\t\t// 封装bean beg\n" +
				"\t\ttemp.set(pdb.getString(i, \"xxx\")); \n" +
				"\t\n" +
				"\t\t// 封装bean end\n" +
				"\t\tlist.add(temp); \n" +
				"\t }\n" +
				"\treturn list;\n" +
				"}");
		
		System.out.println(
				"@Override\n" +
				"public PagingBean getListBy(Bean bean, String sortKey, boolean desc, long offset, int maxPageSize) throws Exception {\n" +
				"\tPagingBean pb = new PagingBean();\n" +
				"\tList<Bean> list = new ArrayList<Bean>();\n" +
				"\tStringBuffer sql = new StringBuffer();\n" +
				"\t// 拼接sql beg\n" +
				"\tsql.append(\"\");\n" +
				"\t\n" +
				"\t// 拼接sql end\n" +
				"\tsql.append(\"where 1=1\");\n" +
				"\tList<String> codition = new ArrayList<String>();\n" +
				"\tif (!StringUtil.isBlank(bean.get())) {\n" +
				"\t\tsql.append(\" and xxx = ?\"); //sql.append(\" and xxx like ?\");\n" +
				"\t\tcodition.add(StringUtil.deNull(bean.get()));//codition.add(\"%\"+StringUtil.deNull(bean.get())+\"%\");\n" +
				"\t}\n" +
				"\tif (StringUtil.nullOrBlank(sortKey)){\n" +
				"\t\tsql.append(\" order by xxx\");\n" +
				"\t} else {\n" +
				"\t\tsql.append(\" order by \" + sortKey + (desc ? \" desc\" : \" asc\"));\n" +
				"\t}\n" +
				"\tPreparedDBUtil pdb = new PreparedDBUtil();\n" +
				"\tpdb.preparedSelect(dsName, sql.toString(),offset,maxPageSize);\n" +
				"\tint c=1; \n" +
				"\tfor (int i = 0; i < codition.size(); i++) { \n" +
				"\t\tpdb.setString(c++, codition.get(i)); \n" +
				"\t }\n" +
				"\tpdb.executePrepared(); \n" +
				"\tfor (int i = 0; i < pdb.size(); i++) { \n" +
				"\t\tBean temp = new Bean(); \n" +
				"\t\t// 封装bean beg\n" +
				"\t\ttemp.set(pdb.getString(i, \"xxx\")); \n" +
				"\t\n" +
				"\t\t// 封装bean end\n" +
				"\t\tlist.add(temp); \n" +
				"\t }\n" +
				"\tpb.setList(list);\n" +
				"\tpb.setTotalSize((long) pdb.getTotalSize());\n" +
				"\treturn pb;\n" +
				"}");
		
		System.out.println(
				"@Override\n" +
				"public void delete(String id) throws Exception {\n" +
				"\tString sql = \"\";\n" +
				"\tPreparedDBUtil pdb = new PreparedDBUtil();\n" +
				"\tpdb.preparedUpdate(dsName, sql);\n" +
				"\tint c=1; \n" +
				"\tpdb.setString(c++, id); \n" +
				"\t \n" +
				"\tpdb.executePrepared(); \n" +
				"}");
	}
}
