//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 03:26:21 ÏÂÎç CST 
//


package com.cts.elt.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="field1"/>
 *             &lt;enumeration value="field2"/>
 *             &lt;enumeration value="field3"/>
 *             &lt;enumeration value="field4"/>
 *             &lt;enumeration value="field5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SrcField" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="field1"/>
 *             &lt;enumeration value="field2"/>
 *             &lt;enumeration value="srcfield1"/>
 *             &lt;enumeration value="srcfield2"/>
 *             &lt;enumeration value="srcfield3"/>
 *             &lt;enumeration value="srcfield4"/>
 *             &lt;enumeration value="srcfield5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="isprimarykey">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="idtype">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="seqname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nullable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DestField")
public class DestField {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "SrcField", required = true)
    protected String srcField;
    @XmlAttribute
    protected String isprimarykey;
    @XmlAttribute
    protected String idtype;
    @XmlAttribute
    protected String seqname;
    @XmlAttribute
    protected String nullable;
    @XmlAttribute
    protected String defval;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the srcField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcField() {
        return srcField;
    }

    /**
     * Sets the value of the srcField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcField(String value) {
        this.srcField = value;
    }

    /**
     * Gets the value of the isprimarykey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsprimarykey() {
        return isprimarykey;
    }

    /**
     * Sets the value of the isprimarykey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsprimarykey(String value) {
        this.isprimarykey = value;
    }

    /**
     * Gets the value of the idtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * Sets the value of the idtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdtype(String value) {
        this.idtype = value;
    }

    /**
     * Gets the value of the seqname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqname() {
        return seqname;
    }

    /**
     * Sets the value of the seqname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqname(String value) {
        this.seqname = value;
    }

    /**
     * Gets the value of the nullable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNullable() {
        return nullable;
    }

    /**
     * Sets the value of the nullable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNullable(String value) {
        this.nullable = value;
    }

    /**
     * Gets the value of the defval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefval() {
        return defval;
    }

    /**
     * Sets the value of the defval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefval(String value) {
        this.defval = value;
    }

}
